/* tslint:disable */
/* eslint-disable */
/**
 * Todo
 * My Todo list API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: deven.phillips@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewTodo
 */
export interface NewTodo {
    /**
     * 
     * @type {string}
     * @memberof NewTodo
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof NewTodo
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewTodo
     */
    'id'?: string;
}

